In [1]:
import numpy as np

In [4]:
a = np.zeros((5,5))

In [6]:
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
a.size,a.shape,a.ndim

(25, (5, 5), 2)

In [9]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [10]:
np.full((5,5),8)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
b = np.arange(1,11).reshape((2,5))
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [14]:
b.size,b.shape

(10, (2, 5))

In [17]:
type(np.random)

module

In [19]:
np.random.rand(10,2)

array([[0.92543754, 0.46661199],
       [0.47241061, 0.5008778 ],
       [0.1235085 , 0.94704173],
       [0.51248669, 0.08406291],
       [0.83195686, 0.86517052],
       [0.75889305, 0.02940911],
       [0.71759089, 0.96004391],
       [0.45625763, 0.0060647 ],
       [0.40610548, 0.1232474 ],
       [0.62171154, 0.1252951 ]])

In [20]:
np.random.randint(1,18,(3,3))

array([[ 1,  4,  7],
       [15, 15, 17],
       [10, 17, 12]])

In [23]:
np.linspace(1,1000,8)

array([   1.        ,  143.71428571,  286.42857143,  429.14285714,
        571.85714286,  714.57142857,  857.28571429, 1000.        ])

In [25]:
c = np.arange(1,31).reshape(5,2,3)
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]],

       [[25, 26, 27],
        [28, 29, 30]]])

In [27]:
t = np.array([10,20])

In [28]:
t.size,t.shape

(2, (2,))