In [1]:
import numpy as np

In [3]:
a = np.random.randint(1,10,5)
a

array([7, 9, 3, 5, 1])

In [4]:
a[[0,3]]

array([7, 5])

In [5]:
a[range(4)]

array([7, 9, 3, 5])

In [6]:
index = [1,2,4]

In [7]:
a[index]

array([9, 3, 1])

#Boolean Indexing

#Boolean Indexing

In [8]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [9]:
a[[False,True,False,True,False]]

array([1, 3])

#vectorization Operations

In [17]:
a%2,a+2

(array([0, 1, 0, 1, 0], dtype=int32), array([2, 3, 4, 5, 6]))

In [11]:
a

array([0, 1, 2, 3, 4])

In [19]:
type(a[a%2])

numpy.ndarray

In [14]:
a[a%2 == 0]

array([0, 2, 4])

In [15]:
a[a%2] == 0

array([ True, False,  True, False,  True])

In [16]:
a%2 ==0

array([ True, False,  True, False,  True])

# Masking

In [20]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
nos_grater_than_5 = a>5
nos_grater_than_5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [26]:
a

array([ 1,  2,  3,  4,  5,  8,  9, 10, 11, 12])

In [23]:
a[nos_grater_than_5] = a[nos_grater_than_5]+2

In [24]:
a

array([ 1,  2,  3,  4,  5,  8,  9, 10, 11, 12])

#Axis

# Axis

In [33]:
a = np.arange(10).reshape(5,2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [31]:
a.sum()

45

In [32]:
a.sum(axis= 1)

array([ 1,  5,  9, 13, 17])

In [34]:
a.diagonal()

array([0, 3])