In [1]:
import numpy as np

In [2]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
a[-2:]

array([ 9, 10])

In [4]:
a[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [5]:
a[8:6:-1]

array([9, 8])

In [7]:
a = np.arange(1,26).reshape(5,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [8]:
a[-1,-1]

25

In [9]:
a[1,:]

array([ 6,  7,  8,  9, 10])

In [11]:
a[:3,:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [12]:
a[:,-5]

array([ 1,  6, 11, 16, 21])

In [13]:
a[-2:,-2:]

array([[19, 20],
       [24, 25]])